image: docker:git
services:
- docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com


build_fedora:
  script:
    - docker build -t registry.gitlab.com/gbraad/kubernetes-client:fedora ./fedora 
    - docker push registry.gitlab.com/gbraad/kubernetes-client:fedora
  only:
    - master

