image: docker:git
services:
- docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com


build_alpine:
  script:
    - docker build -t registry.gitlab.com/gbraad/kubernetes-client:alpine ./alpine 
    - docker push registry.gitlab.com/gbraad/kubernetes-client:alpine
  only:
    - master

build_fedora:
  script:
    - docker build -t registry.gitlab.com/gbraad/kubernetes-client:fedora ./fedora 
    - docker push registry.gitlab.com/gbraad/kubernetes-client:fedora
  only:
    - master

build_static:
  script:
    - cd scratch
    - wget http://storage.googleapis.com/kubernetes-release/release/v1.3.4/bin/linux/amd64/kubectl
    - chmod +x kubectl
    - docker build -t registry.gitlab.com/gbraad/kubernetes-client:static . 
    - docker push registry.gitlab.com/gbraad/kubernetes-client:static
  only:
    - master


